IS445HW6JLR/Models/PhoneNumberModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IS445HW6JLR.Models
{
    public class PhoneNumberModel
    {
        [DisplayName("Phone Number")]
        [Required]
        public string PhoneNumber { get; set; }
    }
}

IS445HW6JLR/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IS445HW6JLR.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.PageTitle = "Home Page";
            ViewBag.TitleMessage = "IS445HW6";
            ViewBag.Message = "Click on a task link to see some string manipulation at work in both C# and Javascript.";

            return View();
        }
    }
}

IS445HW6JLR/Controllers/TaskController.cs
using IS445HW6JLR.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace IS445HW6JLR.Controllers
{
    public class TaskController : Controller
    {
        //
        // GET: /Task/Task1

        public ActionResult Task1()
        {
            ViewBag.PageTitle = "Task 1";
            ViewBag.TitleMessage = "Task 1";
            ViewBag.Message = "Format a phone number into a standard format using C#.";

            return View();
        }

        //
        // GET: /Task/Task1Format
        [HttpGet]
        public ActionResult Task1Format()
        {
            ViewBag.PageTitle = "Task 1";
            ViewBag.TitleMessage = "Task 1";
            ViewBag.Message = "Format a phone number into a standard format using C#.";
            PhoneNumberModel phoneNumModel = new PhoneNumberModel();

            return View(phoneNumModel);
        }

        //
        // POST: /Task/Task1Format
        [HttpPost]
        public ActionResult Task1Format(PhoneNumberModel phoneNumModel)
        {
            string regexPattern = @"[0-9]+";
            string inputString = phoneNumModel.PhoneNumber;
            StringBuilder outputSB = new StringBuilder();
            MatchCollection regexMatchColl = Regex.Matches(inputString, regexPattern);

            foreach (Match regexMatch in regexMatchColl)
            {
                outputSB.Append(regexMatch.Value);
            }

            if (outputSB.Length != 10)
            {
                //We've got a problem.  Return to the user and let them know that they didn't submit
                //a valid 10 digit phone number
                ModelState.AddModelError("PhoneNumber", "The phone number must have 10 digits");

                ViewBag.PageTitle = "Task 1";
                ViewBag.TitleMessage = "Task 1";
                ViewBag.Message = "Format a phone number into a standard format using C#.";

                return View(phoneNumModel);
            }

            else
            {
                //Start with:
                //xxxxxxxxxx
                //0123456789  <--Index
                outputSB.Insert(0, "(");

                //Now we have:
                //(xxxxxxxxxx
                //01234567890
                outputSB.Insert(4, ") ");

                //Now we have:
                //(xxx) xxxxxxx
                //0123456789012
                outputSB.Insert(9, "-");

                //Finally, it is formatted correctly.
                //(xxx) xxx-xxxx
                PhoneNumberModel newPhoneNumModel = new PhoneNumberModel();
                newPhoneNumModel.PhoneNumber = outputSB.ToString();

                ViewBag.PageTitle = "Task 1";
                ViewBag.TitleMessage = "Task 1";
                ViewBag.Message = "Format a phone number into a standard format using C#.";

                return View("Task1FormatResult", newPhoneNumModel);
            }
        }

        //
        // GET: /Task/Task2
        public ActionResult Task2()
        {
            ViewBag.PageTitle = "Task 2";
            ViewBag.TitleMessage = "Task 2";
            ViewBag.Message = "Reverse the text of a provided sentence using Javascript.";

            return View();
        }

        public ActionResult Task2Format()
        {
            ViewBag.PageTitle = "Task 2";
            ViewBag.TitleMessage = "Task 2";
            ViewBag.Message = "Reverse the text of a provided sentence using Javascript.";

            return View();
        }
    }
}

IS445HW6JLR/Views/Home/Index.cshtml
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.TitleMessage.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                This homework will focus on manipulating a <mark>phone number</mark> and a <mark>sentence</mark> within
                the context of an ASP.NET MVC4 site.  Click a link for one of the tasks to get started!
            </p>
        </div>
    </section>
}
<h3>Homework 6 accomplishes the following tasks:</h3>
<ol class="round">
    <li class="one">
        <h5>Task 1</h5>
        <p>Task 1 is a page that takes a 10 digit telephone number as input and then formats the telephone number into a standard format.</p>
        <p>For example, if we input 5629851111, the number would be formatted as (562) 985-1111</p>
        <p>@Html.ActionLink("Go to Task 1", "Task1", "Task")</p>
    </li>

    <li class="two">
        <h5>Task 2</h5>
        <p>Task 2 is a page that takes a line of text as input and then reverses the text.</p>
        <p>For example, if we input "Welcome to IS445: Web Application development", the line of text would be changed to "development Application Web IS445: to Welcome"</p>
        <p>@Html.ActionLink("Go to Task 2", "Task2", "Task")</p>
    </li>
</ol>

IS445HW6JLR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.PageTitle - IS445 HW6</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @RenderSection("headerItems", required: false)
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">IS445 Homework 6</p>
                </div>
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Task 1", "Task1", "Task")</li>
                            <li>@Html.ActionLink("Task 2", "Task2", "Task")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - IS445 HW6</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

IS445HW6JLR/Views/Task/Task1.cshtml
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.TitleMessage.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                This task will format a 10 digit phone number into a standard format: <mark>(xxx) xxx-xxxx</mark> using C#.
            </p>
        </div>
    </section>
}

<h3>Task 1</h3>
<p>Task 1 will take a 10 digit telephone number as input and then format the telephone number into a standard format.</p>
<p>For example, if we input 5629851111, the number would be formatted as (562) 985-1111</p>
<p>@Html.ActionLink("Begin Task 1", "Task1Format", "Task")</p>

IS445HW6JLR/Views/Task/Task1Format.cshtml
@model IS445HW6JLR.Models.PhoneNumberModel

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.TitleMessage.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                This task will format a 10 digit phone number into a standard format: <mark>(xxx) xxx-xxxx</mark> using C#.
            </p>
        </div>
    </section>
}

@using (Html.BeginForm("Task1Format", "Task"))
{
    <h4>To begin, enter a 10 digit phone number in an format:</h4>
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Task 1 - Format Phone Number</legend>
        <div class="editor-label">
            @Html.LabelFor(pnModel => pnModel.PhoneNumber)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(pnModel => pnModel.PhoneNumber)
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>

        <h4>Now, click the "Format" button to format the number into a standard format.</h4>
        <p>
            <input type="submit" value="Format" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to Task1 Intro", "Task1")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IS445HW6JLR/Views/Task/Task1FormatResult.cshtml
@model IS445HW6JLR.Models.PhoneNumberModel

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.TitleMessage.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                This task will format a 10 digit phone number into a standard format: <mark>(xxx) xxx-xxxx</mark> using C#.
            </p>
        </div>
    </section>
}

<h3>Here's your formatted phone number!</h3>

<fieldset>
    <legend>PhoneNumberModel</legend>
    <div class="display-field">
        @Html.DisplayFor(model => model.PhoneNumber)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Start Over", "Task1Format") |
    @Html.ActionLink("Back to Task1 Intro", "Task1") |
    @Html.ActionLink("Home", "Index", "Home")
</p>

IS445HW6JLR/Views/Task/Task2.cshtml
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.TitleMessage.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                This task will take a sentence, or a series of words, and reverse the order of the words using Javascript.
            </p>
        </div>
    </section>
}

<h3>Task 2</h3>
<p>Task 2 will take a sentence, or a series of words, as input and then reverse the order of the words.</p>
<p>For example, if we input "Welcome to IS445: Web Application development", the line of text would be changed to "development Application Web IS445: to Welcome"</p>
<p>@Html.ActionLink("Begin Task 2", "Task2Format", "Task")</p>

IS445HW6JLR/Views/Task/Task2Format.cshtml
@section headerItems {
    @Styles.Render("~/Content/themes/base/jqueryuiall")
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.TitleMessage.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                This task will take a sentence, or a series of words, and reverse the order of the words using Javascript.
            </p>
        </div>
    </section>
}

<div class="taskContent">
    <form id="task2Form" name="task2Form" action="#" method="get">
        <div class="taskPrompt">
            <h4>To begin, enter a sentence or a series of words:</h4>
            <div class="editor-field">
                <input id="textInput" class="required" type="text" placeholder="Place text here" name="TextInput" />
            </div>
            <h4>Now, click the "Reverse" button to reverse the words.</h4>
            <input id="reverseBtn" type="submit" value="Reverse" />
        </div>
    </form>
    <div class="taskResult">
        <h3>The words have been reversed!</h3>
        <div class="display-field">
            <span id="result"></span>
        </div>
    </div>
</div>

<div class="taskPrompt">
    @Html.ActionLink("Back to Task2 Intro", "Task2")
</div>

<div class="taskResult">
    @Html.ActionLink("Start Over", "Task2Format") |
    @Html.ActionLink("Back to Task2 Intro", "Task2") |
    @Html.ActionLink("Home", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryvalidate")
    @Scripts.Render("~/bundles/jqueryui")
    <script type="text/javascript">
        $(document).ready(function () {
            var reverseText = function (inputString) {
                var wordArr = inputString.split(" ");
                var outputString = "";

                for (var i = wordArr.length - 1; i >= 0; i--) {
                    outputString += wordArr[i] + " ";
                }

                outputString = $.trim(outputString);

                return outputString;
            };

            $("#task2Form").validate({
                submitHandler: function (form) {
                    $(".taskPrompt").effect("puff", 800, function () {
                        $("#result").html(
                            "<mark>" + reverseText($("#textInput").val()) + "</mark>"
                        );
                        $(".taskResult").show(500);
                    });
                },
                messages: {
                    TextInput: "Please enter a series of words"
                }
            });
        });
    </script>
}